apiVersion: v1
kind: Service
metadata:
  name: http-source-controller
spec:
  type: ClusterIP
  selector:
    control-plane: http-source-controller-manager
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
