# permissions for end users to view https.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: http-controller
    app.kubernetes.io/managed-by: kustomize
  name: http-viewer-role
rules:
- apiGroups:
  - openfluxcd.openfluxcd
  resources:
  - https
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - openfluxcd.openfluxcd
  resources:
  - https/status
  verbs:
  - get
