apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: http-source-controller
    app.kubernetes.io/managed-by: kustomize
  name: http-source-controller-leader-election-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: http-source-controller-leader-election-role
subjects:
- kind: ServiceAccount
  name: http-source-controller-manager
  namespace: system
