---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - openfluxcd.mandelsoft.org
  resources:
  - artifacts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - openfluxcd.openfluxcd
  resources:
  - https
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - openfluxcd.openfluxcd
  resources:
  - https/finalizers
  verbs:
  - update
- apiGroups:
  - openfluxcd.openfluxcd
  resources:
  - https/status
  verbs:
  - get
  - patch
  - update
