apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    control-plane: http-source-controller-manager
    app.kubernetes.io/name: http-source-controller
    app.kubernetes.io/managed-by: kustomize
  name: http-source-controller-manager
  namespace: system
